apiVersion: apps/v1
kind: Deployment
metadata:
  name: napp-backend-deployment
  namespace: fullstack-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: napp-backend
  template:
    metadata:
      labels:
        app: napp-backend
    spec:
      containers:
      - name: napp-backend
        image: bilal590/nApp-backend:1.1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
